import combinatorial_aspects_matrices_incidence_hadamard_foundation_canonical_lane_mathlib.GateLemmas
import combinatorial_aspects_matrices_incidence_hadamard_foundation_canonical_lane_mathlib.FinalTheorem
